manifest:
  defaults:
    remote: AkytharPandaaa
    revision: v0.3 # pin all the imports to v0.3

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    # ZMK modules
    - name: zmk-locales
      remote: joelspadin
      revision: main

  self:
    path: config
